---
- name: install ovirt release36 repo (last with allinone)
  yum:
    name: http://resources.ovirt.org/pub/yum-repo/ovirt-release36.rpm
    state: installed
- name: install updates
  yum:
    name: '*'
    state: latest
- name: switch to Permissive until I figure out what goes wrong when Enforcing
  selinux:
    policy: targeted
    state: permissive
- name: comment the last 3 lines with Ciphers, MACs and KexAlgorithms temporarily because ovirt install will fail
  lineinfile: 
    dest: /etc/ssh/sshd_config
    regexp: 'Ciphers(.*)$'
    line: '#Ciphers\1'
  notify: 'restart sshd'
- name: comment the last 3 lines with Ciphers, MACs and KexAlgorithms temporarily because ovirt install will fail
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: 'MACs(.*)$'
    line: '#MACs\1'
  notify: 'restart sshd'
- name: comment the last 3 lines with Ciphers, MACs and KexAlgorithms temporarily because ovirt install will fail
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: 'KexAlgorithms(.*)$'
    line: '#KexAlgorithms\1'
  notify: 'restart sshd'
- name: Install ovirt-engine-setup-plugin-allinone
  yum: name=ovirt-engine-setup-plugin-allinone
- name: Prepare engine-setup playbook
  template: 
    src: ovirt-enginesetup.yml.j2
    dest: /etc/ansible/ovirt-enginesetup.yml
