---
- name: install ovirt release36 repo (last with allinone)
  yum:
    name: http://resources.ovirt.org/pub/yum-repo/ovirt-release36.rpm
    state: installed
- name: install updates
  yum:
    name: '*'
    state: latest
- name: install prerequisites
  yum: state=present name={{ item }}
  with_items:
  - firewalld
  - nfs-utils
- name: 'start firewalld'
  systemd:
    state: started
    enabled: yes
    name: firewalld
- name: 'start nfs server'
  systemd:
    state: started
    enabled: yes
    name: nfs-server
- name: switch to Permissive until I figure out what goes wrong when Enforcing
  selinux:
    policy: targeted
    state: permissive
- name: comment the last 3 lines with Ciphers, MACs and KexAlgorithms temporarily because ovirt install will fail
  lineinfile: 
    dest: /etc/ssh/sshd_config
    backup: yes
    regexp: 'Ciphers'
    line: '#Ciphers'
  notify: 'restart sshd'
- name: comment the last 3 lines with Ciphers, MACs and KexAlgorithms temporarily because ovirt install will fail
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: 'MACs'
    line: '#MACs'
  notify: 'restart sshd'
- name: comment the last 3 lines with Ciphers, MACs and KexAlgorithms temporarily because ovirt install will fail
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: 'KexAlgorithms'
    line: '#KexAlgorithms'
  notify: 'restart sshd'
- name: Install ovirt-engine-setup-plugin-allinone
  yum: name=ovirt-engine-setup-plugin-allinone
- name: Prepare engine-setup playbook
  template: 
    src: ovirt-enginesetup.yml.j2
    dest: /etc/ansible/ovirt-enginesetup.yml
